# Generated by Django 3.2.4 on 2021-07-05 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.SmallIntegerField(blank=True, choices=[(1, '经理'), (2, '业务'), (3, '主管'), (4, '商务'), (5, '人事'), (6, '售前'), (7, '技术')], default=None, null=True, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sub_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上级领导'),
        ),
    ]
