# Generated by Django 3.2.4 on 2021-07-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210705_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.SmallIntegerField(blank=True, choices=[(0, '系统管理员'), (1, '经理'), (2, '业务'), (3, '主管'), (4, '商务'), (5, '人事'), (6, '售前'), (7, '技术')], default=None, null=True, verbose_name='角色'),
        ),
    ]
