# Generated by Django 3.2.4 on 2021-06-09 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='客户名称')),
                ('rank', models.SmallIntegerField(choices=[(1, '潜在客户'), (2, '意向客户'), (3, '重点客户')], default=1, verbose_name='客户级别')),
                ('is_deal', models.BooleanField(default=False, verbose_name='是否成交')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='客户网址')),
                ('scale', models.SmallIntegerField(choices=[(1, '0~10人'), (2, '10~50人'), (3, '50~100人'), (4, '100~1000人'), (5, '1000人及以上')], default=1, verbose_name='客户规模')),
                ('nature', models.SmallIntegerField(choices=[(1, '有限责任公司'), (2, '股份有限公司'), (3, '国有企业'), (4, '集体企业'), (5, '私营企业'), (6, '个体工商户'), (7, '合伙企业'), (8, '联营企业'), (9, '股份合作制企业')], default=8, verbose_name='客户性质')),
                ('industry', models.SmallIntegerField(choices=[(1, '机台设备制造商'), (2, '生产制造型企业'), (3, '系统集成商'), (4, '分销商'), (5, '其它')], default=1, verbose_name='客户行业')),
                ('remarks', models.CharField(blank=True, max_length=512, null=True, verbose_name='客户备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
                'db_table': 'customer',
                'ordering': ['-created_at'],
            },
        ),
    ]
