# Generated by Django 3.2.4 on 2021-08-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210826_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_user',
        ),
    ]
