# Generated by Django 3.2.4 on 2021-07-06 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_record', models.IntegerField(default=0, verbose_name='昨日拜访记录')),
                ('yes_phone', models.IntegerField(default=0, verbose_name='昨日外呼数量')),
                ('new_customer', models.IntegerField(default=0, verbose_name='新增客户')),
                ('new_business', models.IntegerField(default=0, verbose_name='新增商机')),
                ('week_record', models.IntegerField(default=0, verbose_name='本周拜访数量')),
                ('week_phone', models.IntegerField(default=0, verbose_name='本周外呼数量')),
                ('week_business', models.IntegerField(default=0, verbose_name='本周商机数量')),
                ('mon_customer', models.IntegerField(default=0, verbose_name='本月客户数量')),
                ('fol_business', models.IntegerField(default=0, verbose_name='跟进商机')),
                ('fin_business', models.IntegerField(default=0, verbose_name='完成商机')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL, verbose_name='业务姓名')),
            ],
            options={
                'verbose_name': '用户数据统计',
                'verbose_name_plural': '用户数据统计',
                'db_table': 'data',
            },
        ),
    ]
