# Generated by Django 3.2.4 on 2021-08-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='mon_business',
            field=models.IntegerField(default=0, verbose_name='本月商机数量'),
        ),
        migrations.AddField(
            model_name='data',
            name='mon_phone',
            field=models.IntegerField(default=0, verbose_name='本月外呼数量'),
        ),
        migrations.AddField(
            model_name='data',
            name='mon_record',
            field=models.IntegerField(default=0, verbose_name='本月拜访数量'),
        ),
        migrations.AddField(
            model_name='data',
            name='week_customer',
            field=models.IntegerField(default=0, verbose_name='本周客户数量'),
        ),
    ]
