# Generated by Django 3.2.4 on 2021-07-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implement',
            name='plan',
        ),
        migrations.AlterField(
            model_name='implement',
            name='report',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='测试报告'),
        ),
    ]
