# Generated by Django 3.2.4 on 2021-07-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210730_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupport',
            old_name='pre_user',
            new_name='user',
        ),
    ]
