# Generated by Django 3.2.4 on 2021-08-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210730_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aftersupport',
            options={'ordering': ['-created_at'], 'verbose_name': '售后支持表', 'verbose_name_plural': '售后支持表'},
        ),
        migrations.AlterModelOptions(
            name='implement',
            options={'ordering': ['-created_at'], 'verbose_name': '实施支持表', 'verbose_name_plural': '实施支持表'},
        ),
        migrations.AlterModelOptions(
            name='presupport',
            options={'ordering': ['-created_at'], 'verbose_name': '售前支持表', 'verbose_name_plural': '售前支持表'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': '维修支持表', 'verbose_name_plural': '维修支持表'},
        ),
        migrations.AddField(
            model_name='presupport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='文件'),
        ),
    ]
