# Generated by Django 3.2.4 on 2021-08-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210818_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftersupport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='文件'),
        ),
        migrations.AddField(
            model_name='implement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='文件'),
        ),
        migrations.AddField(
            model_name='implement',
            name='product',
            field=models.CharField(default=1, max_length=128, verbose_name='产品名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='文件'),
        ),
    ]
