# Generated by Django 3.2.4 on 2021-08-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210823_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implement',
            name='testplan',
        ),
        migrations.AddField(
            model_name='implement',
            name='impplan',
            field=models.CharField(default=1, max_length=256, verbose_name='实施方案'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='implement',
            name='report',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='结果反馈'),
        ),
    ]
