# Generated by Django 3.2.4 on 2021-06-28 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_auto_20210628_1444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='商机名称')),
                ('winning_rate', models.SmallIntegerField(choices=[(1, '0%'), (2, '20%'), (3, '50%'), (4, '80%'), (5, '100%')], default=1, verbose_name='赢单率')),
                ('money', models.CharField(blank=True, max_length=16, null=True, verbose_name='预估金额')),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True, verbose_name='商机备注')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='customer.customer', verbose_name='商机客户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '客户商机',
                'verbose_name_plural': '客户商机',
                'db_table': 'business',
                'ordering': ['-created_at'],
            },
        ),
    ]
