# Generated by Django 3.2.4 on 2021-07-19 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=128, verbose_name='产品名称')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('price', models.CharField(blank=True, max_length=16, null=True, verbose_name='金额')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessproduct', to='business.business', verbose_name='商机')),
            ],
            options={
                'verbose_name': '商机产品',
                'verbose_name_plural': '商机产品',
                'db_table': 'business_product',
            },
        ),
    ]
