# Generated by Django 3.2.4 on 2021-07-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_is_deal'),
        ('business', '0002_businessproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessproduct',
            name='business',
        ),
        migrations.AddField(
            model_name='businessproduct',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='businessproduct', to='customer.customer', verbose_name='商机客户'),
            preserve_default=False,
        ),
    ]
