# Generated by Django 3.2.4 on 2021-07-30 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20210720_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessproduct',
            name='customer',
        ),
        migrations.AddField(
            model_name='businessproduct',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='businessproduct', to='business.business', verbose_name='商机'),
            preserve_default=False,
        ),
    ]
