# Generated by Django 3.2.4 on 2021-09-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='product',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='现用产品'),
        ),
    ]
