# Generated by Django 3.2.4 on 2021-06-28 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_auto_20210628_1444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='联系人姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='联系人电话')),
                ('job', models.SmallIntegerField(choices=[(1, '经理'), (2, '采购'), (3, '技术'), (4, '售后'), (5, '业务'), (6, '其他')], default=1, verbose_name='职称')),
                ('injob', models.SmallIntegerField(choices=[(1, '在职'), (0, '离职')], default=1, verbose_name='是否在职')),
                ('wx', models.CharField(blank=True, max_length=64, null=True, verbose_name='微信')),
                ('qq', models.CharField(blank=True, max_length=64, null=True, verbose_name='QQ')),
                ('email', models.EmailField(blank=True, max_length=64, null=True, verbose_name='电子邮箱')),
                ('hobby', models.CharField(blank=True, max_length=128, null=True, verbose_name='兴趣爱好')),
                ('birthday', models.CharField(blank=True, max_length=64, null=True, verbose_name='生日')),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True, verbose_name='联系人备注')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liaison', to='customer.customer', verbose_name='客户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
                'db_table': 'liaison',
                'ordering': ['-created_at'],
            },
        ),
    ]
